version: '3'

networks:
  cscpassist-net:
    external: false

services:
  cscpassist-controller:
    container_name: cscpassist-controller
    ports:
      - 17037:17037
      - 17037:17037/udp
    image: cscpassist/cscpassist-server:latest
    command: cscpassist-controller -r cscpassist.example.com:17038
    volumes:
      - ./data:/root
    networks:
      - cscpassist-net
    depends_on:
      - cscpassist-intermediary
    restart: unless-stopped

  cscpassist-intermediary:
    container_name: cscpassist-intermediary
    ports:
      - 17038:17038
    image: cscpassist/cscpassist-server:latest
    command: cscpassist-intermediary
    volumes:
      - ./data:/root
    networks:
      - cscpassist-net
    restart: unless-stopped
