#!/bin/sh

# PROVIDE: cscpassist_controller
# REQUIRE: LOGIN
# KEYWORD: shutdown
#
# Add the following lines to /etc/rc.conf.local or /etc/rc.conf
# to enable this service:
#
# cscpassist_controller_enable (bool):            Set to NO by default.
#               Set it to YES to enable cscpassist_controller.
# cscpassist_controller_ip (string):              Set IP address/hostname of relay server to use
#               Defaults to "127.0.0.1", please replace with your server hostname/IP.
# cscpassist_controller_args (string):            Set extra arguments to pass to cscpassist_controller
#               Default is "-r ${cscpassist_controller_ip} -k _".
# cscpassist_controller_user (string):            Set user that cscpassist_controller will run under
#               Default is "root".
# cscpassist_controller_group (string):           Set group that cscpassist_controller will run under
#               Default is "wheel".

. /etc/rc.subr

name=cscpassist_controller
desc="CscpAssist ID/Rendezvous Server"
rcvar=cscpassist_controller_enable

load_rc_config $name

: ${cscpassist_controller_enable:=NO}
: ${cscpassist_controller_ip:=127.0.0.1}
: ${cscpassist_controller_args="-r ${cscpassist_controller_ip} -k _"}
: ${cscpassist_controller_user:=cscpassist}
: ${cscpassist_controller_group:=cscpassist}

pidfile=/var/run/cscpassist_controller.pid
command=/usr/sbin/daemon
procname=/usr/local/sbin/cscpassist-controller
cscpassist_controller_chdir=/var/db/cscpassist-server
command_args="-p ${pidfile} -o /var/log/cscpassist-controller.log ${procname} ${cscpassist_controller_args}"
## If you want the daemon to do its log over syslog, comment out the above line and remove the comment from the below replacement
#command_args="-p ${pidfile} -T ${name} ${procname} ${cscpassist_controller_args}"

start_precmd=cscpassist_controller_startprecmd

cscpassist_controller_startprecmd()
{
    if [ -e ${pidfile} ]; then
        chown ${cscpassist_controller_user}:${cscpassist_controller_group} ${pidfile};
    else
        install -o ${cscpassist_controller_user} -g ${cscpassist_controller_group} /dev/null ${pidfile};
    fi
    if [ -e ${cscpassist_controller_chdir} ]; then
        chown -R ${cscpassist_controller_user}:${cscpassist_controller_group} ${cscpassist_controller_chdir};
        chmod -R 770 ${cscpassist_controller_chdir};
    else
        mkdir -m 770 ${cscpassist_controller_chdir};
        chown ${cscpassist_controller_user}:${cscpassist_controller_group} ${cscpassist_controller_chdir};
    fi
    if [ -e /var/log/cscpassist-controller.log ]; then
        chown -R ${cscpassist_controller_user}:${cscpassist_controller_group} /var/log/cscpassist-controller.log;
        chmod 660 /var/log/cscpassist-controller.log;
    else
        install -o ${cscpassist_controller_user} -g ${cscpassist_controller_group} /dev/null /var/log/cscpassist-controller.log;
        chmod 660 /var/log/cscpassist-controller.log;
    fi
}

run_rc_command "$1"
