#!/bin/sh

# PROVIDE: cscpassist_intermediary
# REQUIRE: LOGIN
# KEYWORD: shutdown
#
# Add the following lines to /etc/rc.conf.local or /etc/rc.conf
# to enable this service:
#
# cscpassist_intermediary_enable (bool):            Set to NO by default.
#               Set it to YES to enable cscpassist_intermediary.
# cscpassist_intermediary_args (string):            Set extra arguments to pass to cscpassist_intermediary
#               Default is "-k _".
# cscpassist_intermediary_user (string):            Set user that cscpassist_intermediary will run under
#               Default is "root".
# cscpassist_intermediary_group (string):           Set group that cscpassist_intermediary will run under
#               Default is "wheel".

. /etc/rc.subr

name=cscpassist_intermediary
desc="CscpAssist Intermediary Server"
rcvar=cscpassist_intermediary_enable

load_rc_config $name

: ${cscpassist_intermediary_enable:=NO}
: ${cscpassist_intermediary_args="-k _"}
: ${cscpassist_intermediary_user:=cscpassist}
: ${cscpassist_intermediary_group:=cscpassist}

pidfile=/var/run/cscpassist_intermediary.pid
command=/usr/sbin/daemon
procname=/usr/local/sbin/cscpassist-intermediary
cscpassist_intermediary_chdir=/var/db/cscpassist-server
command_args="-p ${pidfile} -o /var/log/cscpassist-intermediary.log ${procname} ${cscpassist_intermediary_args}"
## If you want the daemon do its log over syslog comment out the above line and remove the comment from the below replacement
#command_args="-p ${pidfile} -T ${name} ${procname} ${cscpassist_intermediary_args}"

start_precmd=cscpassist_intermediary_startprecmd

cscpassist_intermediary_startprecmd()
{
    if [ -e ${pidfile} ]; then
        chown ${cscpassist_intermediary_user}:${cscpassist_intermediary_group} ${pidfile};
    else
        install -o ${cscpassist_intermediary_user} -g ${cscpassist_intermediary_group} /dev/null ${pidfile};
    fi
    if [ -e ${cscpassist_intermediary_chdir} ]; then
        chown -R ${cscpassist_intermediary_user}:${cscpassist_intermediary_group} ${cscpassist_intermediary_chdir};
        chmod -R 770 ${cscpassist_intermediary_chdir};
    else
        mkdir -m 770 ${cscpassist_intermediary_chdir};
        chown ${cscpassist_intermediary_user}:${cscpassist_intermediary_group} ${cscpassist_intermediary_chdir};
    fi
    if [ -e /var/log/cscpassist-intermediary.log ]; then
        chown -R ${cscpassist_intermediary_user}:${cscpassist_intermediary_group} /var/log/cscpassist-intermediary.log;
        chmod 660 /var/log/cscpassist-intermediary.log;
    else
        install -o ${cscpassist_intermediary_user} -g ${cscpassist_intermediary_group} /dev/null /var/log/cscpassist-intermediary.log;
        chmod 660 /var/log/cscpassist-intermediary.log;
    fi
}

run_rc_command "$1"
